name: Deploy to Google Play

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  distribute:
    name: Distribute bundle to Google Play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Clean build outputs
        run: |
          rm -rf app/build/outputs/bundle/release/*
          echo "Cleaned release bundle directory"

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: List generated files
        run: |
          echo "Files in release directory:"
          ls -la app/build/outputs/bundle/release/

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.YALLA_ALIAS }}
          keyPassword: ${{ secrets.YALLA_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.GOOGLE_PLAY_AUTH }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: uz.yalla.client
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          status: 'completed'
